import { promises as fs } from "node:fs";
import { execFileSync } from "node:child_process";
import * as path from "node:path";
import * as core from "@actions/core";
import * as github from "@actions/github";
import type { Finding } from "./report";
import { maxVersion, compareVersions } from "./version";

export interface Upgrade {
  name: string;
  from: string;
  to: string;
  advisoryIds: string[];
}

const BRANCH = "depsentinel/security-upgrades";

type Section = "dependencies" | "devDependencies" | "optionalDependencies";
const SECTIONS: Section[] = ["dependencies", "devDependencies", "optionalDependencies"];

interface Manifest {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
}

/**
 * Compute the set of upgrades that resolve the given findings.
 * For each package, choose the highest fixed version across its advisories.
 */
export function computeUpgrades(findings: Finding[]): Upgrade[] {
  const byPackage = new Map<string, { from: string; fixes: string[]; ids: string[] }>();

  for (const { advisory } of findings) {
    if (advisory.fixedVersions.length === 0) continue;
    const entry = byPackage.get(advisory.packageName) ?? {
      from: advisory.packageVersion,
      fixes: [],
      ids: [],
    };
    entry.fixes.push(...advisory.fixedVersions);
    entry.ids.push(advisory.id);
    byPackage.set(advisory.packageName, entry);
  }

  const upgrades: Upgrade[] = [];
  for (const [name, { from, fixes, ids }] of byPackage) {
    const to = maxVersion(fixes);
    if (!to) continue;
    // Skip if current resolved version already satisfies the fix.
    if (from && compareVersions(from, to) >= 0) continue;
    upgrades.push({ name, from, to, advisoryIds: [...new Set(ids)] });
  }
  return upgrades;
}

/** Apply upgrades to the manifest file, preserving the section each dep lives in. */
async function applyToManifest(manifestPath: string, upgrades: Upgrade[]): Promise<Upgrade[]> {
  const raw = await fs.readFile(manifestPath, "utf8");
  const manifest = JSON.parse(raw) as Manifest;
  const applied: Upgrade[] = [];

  for (const up of upgrades) {
    for (const section of SECTIONS) {
      const deps = manifest[section];
      if (deps && up.name in deps) {
        deps[up.name] = `^${up.to}`;
        applied.push(up);
        break;
      }
    }
  }

  if (applied.length > 0) {
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  }
  return applied;
}

/** Best-effort lockfile refresh so the PR is actually merge-ready. */
function refreshLockfile(cwd: string): void {
  try {
    execFileSync("npm", ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"], {
      cwd,
      stdio: "pipe",
    });
  } catch (err) {
    core.warning(`Lockfile refresh skipped: ${(err as Error).message}`);
  }
}

function git(args: string[], cwd: string): string {
  return execFileSync("git", args, { cwd, stdio: "pipe" }).toString().trim();
}

function buildPrBody(applied: Upgrade[]): string {
  const lines = [
    "## 🛡️ DepSentinel — automated security upgrades",
    "",
    "This PR upgrades dependencies with known advisories to their fixed versions.",
    "",
    "| Package | From | To | Advisories |",
    "|---------|------|----|------------|",
    ...applied.map(
      (u) => `| \`${u.name}\` | ${u.from || "?"} | \`${u.to}\` | ${u.advisoryIds.join(", ")} |`
    ),
    "",
    "_Generated by DepSentinel. Review the changelog for each upgrade before merging._",
  ];
  return lines.join("\n");
}

/**
 * Create (or update) a branch with security upgrades and open a PR.
 * Returns the PR URL, or null if nothing was applicable.
 */
export async function openUpgradePr(
  token: string,
  manifestPath: string,
  findings: Finding[]
): Promise<string | null> {
  const upgrades = computeUpgrades(findings);
  if (upgrades.length === 0) {
    core.info("No fixed versions available — skipping upgrade PR.");
    return null;
  }

  const applied = await applyToManifest(manifestPath, upgrades);
  if (applied.length === 0) {
    core.info("No matching dependencies found in the manifest — skipping upgrade PR.");
    return null;
  }

  const cwd = path.dirname(manifestPath);
  refreshLockfile(cwd);

  const { owner, repo } = github.context.repo;
  const repoRoot = process.env.GITHUB_WORKSPACE || cwd;

  // Configure identity and an authenticated remote for the push.
  git(["config", "user.name", "depsentinel[bot]"], repoRoot);
  git(["config", "user.email", "depsentinel[bot]@users.noreply.github.com"], repoRoot);
  git(
    ["remote", "set-url", "origin", `https://x-access-token:${token}@github.com/${owner}/${repo}.git`],
    repoRoot
  );

  git(["checkout", "-B", BRANCH], repoRoot);
  git(["add", "-A"], repoRoot);

  // Nothing staged means the manifest already matched the target — bail gracefully.
  const status = git(["status", "--porcelain"], repoRoot);
  if (!status) {
    core.info("Working tree already up to date — no upgrade PR needed.");
    return null;
  }

  git(["commit", "-m", `chore(security): upgrade ${applied.length} vulnerable dependency(ies)`], repoRoot);
  git(["push", "--force", "origin", BRANCH], repoRoot);

  const octokit = github.getOctokit(token);
  const base = github.context.payload.repository?.default_branch || "main";

  const existing = await octokit.rest.pulls.list({
    owner,
    repo,
    state: "open",
    head: `${owner}:${BRANCH}`,
  });

  if (existing.data.length > 0) {
    const pr = existing.data[0];
    await octokit.rest.pulls.update({
      owner,
      repo,
      pull_number: pr.number,
      body: buildPrBody(applied),
    });
    return pr.html_url;
  }

  const created = await octokit.rest.pulls.create({
    owner,
    repo,
    base,
    head: BRANCH,
    title: `🛡️ Security: upgrade ${applied.length} vulnerable dependency(ies)`,
    body: buildPrBody(applied),
  });
  return created.data.html_url;
}
