import * as github from "@actions/github";
import type { AiAssessment } from "./ai";
import type { Advisory } from "./osv";

export interface Finding {
  advisory: Advisory;
  assessment: AiAssessment;
}

const ISSUE_MARKER = "<!-- depsentinel-report -->";
const ISSUE_TITLE = "🛡️ DepSentinel: dependency security report";

const SEVERITY_EMOJI: Record<string, string> = {
  CRITICAL: "🔴",
  HIGH: "🟠",
  MODERATE: "🟡",
  LOW: "⚪",
  UNKNOWN: "⚫",
};

export function buildReport(findings: Finding[]): string {
  if (findings.length === 0) {
    return `${ISSUE_MARKER}\n## 🛡️ DepSentinel\n\nNo dependency advisories met the configured severity threshold. ✅`;
  }

  const lines: string[] = [
    ISSUE_MARKER,
    "## 🛡️ DepSentinel security report",
    "",
    `Found **${findings.length}** advisory finding(s). Each entry includes an AI impact analysis.`,
    "",
  ];

  // Highest severity first.
  const order = ["CRITICAL", "HIGH", "MODERATE", "LOW", "UNKNOWN"];
  const sorted = [...findings].sort(
    (a, b) =>
      order.indexOf(a.advisory.severity) - order.indexOf(b.advisory.severity)
  );

  for (const { advisory, assessment } of sorted) {
    const emoji = SEVERITY_EMOJI[advisory.severity] ?? "⚫";
    lines.push(
      `### ${emoji} ${advisory.packageName}@${advisory.packageVersion} — ${advisory.id}`,
      "",
      `**Severity:** ${advisory.severity}  |  **Reachability confidence:** ${assessment.reachabilityConfidence}`,
      "",
      `> ${advisory.summary}`,
      "",
      `**AI impact analysis:** ${assessment.impact}`,
      "",
      `**Recommended action:** ${assessment.recommendation}`,
      ""
    );
    if (advisory.fixedVersions.length) {
      lines.push(`**Fixed in:** ${advisory.fixedVersions.join(", ")}`, "");
    }
    if (advisory.references.length) {
      lines.push(
        "**References:**",
        ...advisory.references.map((r) => `- ${r}`),
        ""
      );
    }
    lines.push("---", "");
  }

  lines.push(
    "_Generated by [DepSentinel](https://github.com/marketplace/actions/depsentinel). Powered by OSV.dev advisories + AI impact analysis._"
  );
  return lines.join("\n");
}

/**
 * Create the report issue, or update the existing one if DepSentinel already opened one.
 * Returns the issue URL.
 */
export async function upsertReportIssue(
  token: string,
  body: string
): Promise<string> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  const existing = await findExistingIssue(octokit, owner, repo);

  if (existing) {
    const { data } = await octokit.rest.issues.update({
      owner,
      repo,
      issue_number: existing,
      body,
    });
    return data.html_url;
  }

  const { data } = await octokit.rest.issues.create({
    owner,
    repo,
    title: ISSUE_TITLE,
    body,
    labels: ["security", "depsentinel"],
  });
  return data.html_url;
}

async function findExistingIssue(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string
): Promise<number | null> {
  const { data } = await octokit.rest.issues.listForRepo({
    owner,
    repo,
    state: "open",
    labels: "depsentinel",
    per_page: 20,
  });
  const match = data.find(
    (i) => !i.pull_request && (i.body ?? "").includes(ISSUE_MARKER)
  );
  return match ? match.number : null;
}
